"""FreshForge package."""

from freshforge.matrix import (
    ExpandedWorkflowCase,
    MatrixAxis,
    MatrixAxisValue,
    MatrixCase,
    WorkflowMatrixPlan,
    WorkflowMatrixPlanCase,
    WorkflowMatrixRunCase,
    WorkflowMatrixRunResult,
    WorkflowMatrixSpec,
    WorkflowMatrixSummary,
    expand_workflow_matrix,
    load_workflow_matrix,
    plan_workflow_matrix,
    run_workflow_matrix,
)
from freshforge.providers import (
    FixtureProvider,
    NodeTypeMetadata,
    ProviderMetadata,
    ProviderReference,
    ProviderRegistry,
    ProviderResolution,
    discover_entry_point_providers,
    fixture_provider_factory,
)
from freshforge.records import (
    Diagnostic,
    DiagnosticSeverity,
    NodeRunResult,
    NodeRunSummary,
    PlannedNode,
    ProviderRunResult,
    RunPlan,
    RunStatus,
    WorkflowNode,
    WorkflowRunResult,
    WorkflowRunSummary,
    WorkflowSpec,
)

__version__ = "0.1.0a3"

__all__ = [
    "Diagnostic",
    "DiagnosticSeverity",
    "ExpandedWorkflowCase",
    "FixtureProvider",
    "MatrixAxis",
    "MatrixAxisValue",
    "MatrixCase",
    "NodeTypeMetadata",
    "NodeRunResult",
    "NodeRunSummary",
    "PlannedNode",
    "ProviderMetadata",
    "ProviderReference",
    "ProviderRegistry",
    "ProviderResolution",
    "ProviderRunResult",
    "RunPlan",
    "RunStatus",
    "WorkflowMatrixPlan",
    "WorkflowMatrixPlanCase",
    "WorkflowMatrixRunCase",
    "WorkflowMatrixRunResult",
    "WorkflowMatrixSpec",
    "WorkflowMatrixSummary",
    "WorkflowNode",
    "WorkflowRunResult",
    "WorkflowRunSummary",
    "WorkflowSpec",
    "__version__",
    "discover_entry_point_providers",
    "expand_workflow_matrix",
    "fixture_provider_factory",
    "load_workflow_matrix",
    "plan_workflow_matrix",
    "run_workflow_matrix",
]
